//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.237
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Neovolve.Toolkit.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Neovolve.Toolkit.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - {1}.
        /// </summary>
        internal static string BusinessFailureException_FailureMessageFormat {
            get {
                return ResourceManager.GetString("BusinessFailureException_FailureMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following business failures have been encountered:
        ///{0}.
        /// </summary>
        internal static string BusinessFailureException_MessageHeader {
            get {
                return ResourceManager.GetString("BusinessFailureException_MessageHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown failure.
        /// </summary>
        internal static string BusinessFailureException_UnknownFailure {
            get {
                return ResourceManager.GetString("BusinessFailureException_UnknownFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The endpoint configuration for contract type &apos;{0}&apos; could not be automatically determined as configuration defines multiple named endpoints..
        /// </summary>
        internal static string ChannelProxyHandler_MultipleNamedEndpointConfigurationsFoundForContract {
            get {
                return ResourceManager.GetString("ChannelProxyHandler_MultipleNamedEndpointConfigurationsFoundForContract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The endpoint configuration for contract type &apos;{0}&apos; could not be automatically determined as configuration defines multiple unnamed endpoints..
        /// </summary>
        internal static string ChannelProxyHandler_MultipleUnnamedEndpointConfigurationsFoundForContract {
            get {
                return ResourceManager.GetString("ChannelProxyHandler_MultipleUnnamedEndpointConfigurationsFoundForContract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No configuration could be found for service type &apos;{0}&apos;..
        /// </summary>
        internal static string ChannelProxyHandler_NoEndpointConfigurationForServiceType {
            get {
                return ResourceManager.GetString("ChannelProxyHandler_NoEndpointConfigurationForServiceType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No configuration value found for key &apos;{0}&apos; where a value is required..
        /// </summary>
        internal static string ConfigurationManagerStore_RequiredValueMissing {
            get {
                return ResourceManager.GetString("ConfigurationManagerStore_RequiredValueMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom user name password validation is not enabled as was expected..
        /// </summary>
        internal static string CustomUserNamePasswordValidationNotEnabled {
            get {
                return ResourceManager.GetString("CustomUserNamePasswordValidationNotEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type &apos;{0}&apos; cannot be cast as type &apos;{1}&apos;..
        /// </summary>
        internal static string InvalidCastExceptionMessage {
            get {
                return ResourceManager.GetString("InvalidCastExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid configuration section type for section name &apos;{0}&apos;. The type &apos;{1}&apos; was expected, but &apos;{2}&apos; was found..
        /// </summary>
        internal static string InvalidConfigurationSectionTypeExceptionMessage {
            get {
                return ResourceManager.GetString("InvalidConfigurationSectionTypeExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type &apos;{0}&apos; loaded from configuration with key &apos;{1}&apos; is the incorrect type. It is not assignable to &apos;{2}&apos;..
        /// </summary>
        internal static string InvalidTypeLoadFromConfigurationFailed {
            get {
                return ResourceManager.GetString("InvalidTypeLoadFromConfigurationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assembly: .
        /// </summary>
        internal static string MemberTrace_AssemblyTitle {
            get {
                return ResourceManager.GetString("MemberTrace_AssemblyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type: .
        /// </summary>
        internal static string MemberTrace_DeclaringTypeTitle {
            get {
                return ResourceManager.GetString("MemberTrace_DeclaringTypeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Environment identity: .
        /// </summary>
        internal static string MemberTrace_EnvironmentIdentityTitle {
            get {
                return ResourceManager.GetString("MemberTrace_EnvironmentIdentityTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Machine: .
        /// </summary>
        internal static string MemberTrace_MachineNameTitle {
            get {
                return ResourceManager.GetString("MemberTrace_MachineNameTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main module:.
        /// </summary>
        internal static string MemberTrace_MailModuleTitle {
            get {
                return ResourceManager.GetString("MemberTrace_MailModuleTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method: .
        /// </summary>
        internal static string MemberTrace_MethodNameTitle {
            get {
                return ResourceManager.GetString("MemberTrace_MethodNameTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operating System: .
        /// </summary>
        internal static string MemberTrace_OperatingSystemTitle {
            get {
                return ResourceManager.GetString("MemberTrace_OperatingSystemTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thread identity: .
        /// </summary>
        internal static string MemberTrace_ThreadIdentityTitle {
            get {
                return ResourceManager.GetString("MemberTrace_ThreadIdentityTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thread name: .
        /// </summary>
        internal static string MemberTrace_ThreadNameTitle {
            get {
                return ResourceManager.GetString("MemberTrace_ThreadNameTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to write any trace messages because the MemberTrace instance is already disposed..
        /// </summary>
        internal static string MemberTraceDisposedExceptionMessage {
            get {
                return ResourceManager.GetString("MemberTraceDisposedExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No custom user name password validator has been configured..
        /// </summary>
        internal static string NoCustomUserNamePasswordValidatorConfigured {
            get {
                return ResourceManager.GetString("NoCustomUserNamePasswordValidatorConfigured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No password has been provided..
        /// </summary>
        internal static string NoPasswordProvided {
            get {
                return ResourceManager.GetString("NoPasswordProvided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No user name has been provided..
        /// </summary>
        internal static string NoUserNameProvided {
            get {
                return ResourceManager.GetString("NoUserNameProvided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}. {1}.
        /// </summary>
        internal static string RecordTrace_AdditionalParameterOutput {
            get {
                return ResourceManager.GetString("RecordTrace_AdditionalParameterOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional Parameters:.
        /// </summary>
        internal static string RecordTrace_AdditionalParametersHeader {
            get {
                return ResourceManager.GetString("RecordTrace_AdditionalParametersHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unknown system failure has occurred..
        /// </summary>
        internal static string SystemFailureException_UnknownFailure {
            get {
                return ResourceManager.GetString("SystemFailureException_UnknownFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current ActivityTrace instance is not running and cannot write the event..
        /// </summary>
        internal static string TraceActivityNotRunningExceptionMessage {
            get {
                return ResourceManager.GetString("TraceActivityNotRunningExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current ActivityTrace instance is already running and cannot be started or resumed..
        /// </summary>
        internal static string TraceActivityRunningExceptionMessage {
            get {
                return ResourceManager.GetString("TraceActivityRunningExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The ActivityId of the current ActivityTrace does not match the current activity in Trace.CorrelationManager..
        /// </summary>
        internal static string TraceActivityStackCorruptedExceptionMessage {
            get {
                return ResourceManager.GetString("TraceActivityStackCorruptedExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current ActivityTrace instance is suspended and must be resumed before writing any further events..
        /// </summary>
        internal static string TraceActivitySuspendedExceptionMessage {
            get {
                return ResourceManager.GetString("TraceActivitySuspendedExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to determine a TraceSource name to use or the TraceSource could not be loaded..
        /// </summary>
        internal static string TraceSourceLoadExceptionMessage {
            get {
                return ResourceManager.GetString("TraceSourceLoadExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load type &apos;{0}&apos; defined in configuration with key &apos;{1}&apos;. An instance of &apos;{2}&apos; could not be created..
        /// </summary>
        internal static string TypeLoadFromConfigurationKeyFailed {
            get {
                return ResourceManager.GetString("TypeLoadFromConfigurationKeyFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No matching configuration was found to load a type related to type &apos;{0}&apos;.
        /// </summary>
        internal static string TypeResolver_TypeNotResolvedFromConfiguration {
            get {
                return ResourceManager.GetString("TypeResolver_TypeNotResolvedFromConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type related to type &apos;{0}&apos; could not be found with configuration key &apos;{1}&apos;.
        /// </summary>
        internal static string TypeResolver_TypeNotResolvedFromConfigurationKey {
            get {
                return ResourceManager.GetString("TypeResolver_TypeNotResolvedFromConfigurationKey", resourceCulture);
            }
        }
    }
}
