//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.237
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Neovolve.Toolkit.Unity.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Neovolve.Toolkit.Unity.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The application setting with key &apos;{0}&apos; and value &apos;{1}&apos; cannot be converted to type &apos;{2}&apos;.
        /// </summary>
        internal static string AppSettingsParameterValueElement_CannotConvertAppSettingValue {
            get {
                return ResourceManager.GetString("AppSettingsParameterValueElement_CannotConvertAppSettingValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type &apos;{0}&apos; does not inherit from &apos;{1}&apos;..
        /// </summary>
        internal static string AppSettingsParameterValueElement_InvalidType {
            get {
                return ResourceManager.GetString("AppSettingsParameterValueElement_InvalidType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type &apos;{0}&apos; could not be loaded..
        /// </summary>
        internal static string AppSettingsParameterValueElement_TypeLoadFailure {
            get {
                return ResourceManager.GetString("AppSettingsParameterValueElement_TypeLoadFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An instance has already been assigned to this node..
        /// </summary>
        internal static string BuildTreeNode_InstanceAlreadyAssigned_ExceptionMessage {
            get {
                return ResourceManager.GetString("BuildTreeNode_InstanceAlreadyAssigned_ExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build tree constructed out of order. Build key &apos;{0}&apos; was expected but build key &apos;{1}&apos; was provided..
        /// </summary>
        internal static string BuildTreeTracker_BuildTreeConstructedOutOfOrder {
            get {
                return ResourceManager.GetString("BuildTreeTracker_BuildTreeConstructedOutOfOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No connection string configuration found for key &apos;{0}&apos;..
        /// </summary>
        internal static string ConnectionStringParameterValueElement_ConnectionStringKeyNotFound {
            get {
                return ResourceManager.GetString("ConnectionStringParameterValueElement_ConnectionStringKeyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection string injection only supports the String and ConnectionStringSettings types but injection is requested for the type &apos;{0}&apos;..
        /// </summary>
        internal static string ConnectionStringParameterValueElement_InvalidParameterType {
            get {
                return ResourceManager.GetString("ConnectionStringParameterValueElement_InvalidParameterType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (null).
        /// </summary>
        internal static string NullValueMarker {
            get {
                return ResourceManager.GetString("NullValueMarker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parameter type &apos;{0}&apos; must be an interface or inherit from MarshalByRefObject to have a proxy created for it..
        /// </summary>
        internal static string ProxyDependencyResolverPolicy_TypeNotInterfaceOrMarshalByRefObject_ExceptionMessageFormat {
            get {
                return ResourceManager.GetString("ProxyDependencyResolverPolicy_TypeNotInterfaceOrMarshalByRefObject_ExceptionMessa" +
                        "geFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Unity configuration was found..
        /// </summary>
        internal static string UnityContainerResolver_ConfigurationSectionNotFound {
            get {
                return ResourceManager.GetString("UnityContainerResolver_ConfigurationSectionNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The default Unity container was not found in configuration..
        /// </summary>
        internal static string UnityContainerResolver_DefaultContainerNotFound {
            get {
                return ResourceManager.GetString("UnityContainerResolver_DefaultContainerNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Unity container with the name &apos;{0}&apos; was not found in configuration..
        /// </summary>
        internal static string UnityContainerResolver_NamedContainerNotFound {
            get {
                return ResourceManager.GetString("UnityContainerResolver_NamedContainerNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Unity containers have been configured..
        /// </summary>
        internal static string UnityContainerResolver_NoContainerConfigured {
            get {
                return ResourceManager.GetString("UnityContainerResolver_NoContainerConfigured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The ServiceType value must not null..
        /// </summary>
        internal static string UnityServiceBehavior_ApplyDispatchBehavior_NullServiceType {
            get {
                return ResourceManager.GetString("UnityServiceBehavior_ApplyDispatchBehavior_NullServiceType", resourceCulture);
            }
        }
    }
}
