//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Neovolve.Toolkit.Workflow.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Neovolve.Toolkit.Workflow.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No child activities are defined.
        /// </summary>
        internal static string Activity_NoChildActivitiesDefined {
            get {
                return ResourceManager.GetString("Activity_NoChildActivitiesDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Code value must be provided if a Description value is provided..
        /// </summary>
        internal static string BusinessFailureEvaluator_CodeNotBound {
            get {
                return ResourceManager.GetString("BusinessFailureEvaluator_CodeNotBound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only the Failure property must be specified or Code and Description, not both..
        /// </summary>
        internal static string BusinessFailureEvaluator_ConflictingFailureInformationBound {
            get {
                return ResourceManager.GetString("BusinessFailureEvaluator_ConflictingFailureInformationBound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Description value must be provided if a Code value is provided..
        /// </summary>
        internal static string BusinessFailureEvaluator_DescriptionNotBound {
            get {
                return ResourceManager.GetString("BusinessFailureEvaluator_DescriptionNotBound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Either the Failure property must be specified or Code and Description..
        /// </summary>
        internal static string BusinessFailureEvaluator_FailureInformationNotBound {
            get {
                return ResourceManager.GetString("BusinessFailureEvaluator_FailureInformationNotBound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This activity will always throw an exception with no Condition property set..
        /// </summary>
        internal static string BusinessFailureEvaluator_NoConditionBoundWarning {
            get {
                return ResourceManager.GetString("BusinessFailureEvaluator_NoConditionBoundWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scope contains a BusinessFailureEvaluator defined by a different generic type. BusinessFailureEvaluators with a different generic type will throw failures directly rather than collating the failures in this scope activity..
        /// </summary>
        internal static string BusinessFailureScope_EvaluatorWithDifferentTypeDetected {
            get {
                return ResourceManager.GetString("BusinessFailureScope_EvaluatorWithDifferentTypeDetected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A value of type {0} was expected but a value of {1} was provided..
        /// </summary>
        internal static string ExecuteBookmark_InvalidBookmarkValueTypeProvided {
            get {
                return ResourceManager.GetString("ExecuteBookmark_InvalidBookmarkValueTypeProvided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Receive activity is required as a child activity..
        /// </summary>
        internal static string OperationIdentityInspector_NullBodyFailure {
            get {
                return ResourceManager.GetString("OperationIdentityInspector_NullBodyFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The operation identity type expected was {0} but the identity type {1} was detected..
        /// </summary>
        internal static string OperationIdentityInspector_UnexpectedIdentityType {
            get {
                return ResourceManager.GetString("OperationIdentityInspector_UnexpectedIdentityType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type specified does not derived from System.Exception..
        /// </summary>
        internal static string Retry_InvalidExceptionType {
            get {
                return ResourceManager.GetString("Retry_InvalidExceptionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The exception type &apos;{0}&apos; does not define a constructor with parameter of message..
        /// </summary>
        internal static string SystemFailureEvaluator_MessageConstructorNotFound {
            get {
                return ResourceManager.GetString("SystemFailureEvaluator_MessageConstructorNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The exception type &apos;{0}&apos; does not define a constructor with parameter of paramName..
        /// </summary>
        internal static string SystemFailureEvaluator_ParamNameConstructorNotFound {
            get {
                return ResourceManager.GetString("SystemFailureEvaluator_ParamNameConstructorNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The exception type &apos;{0}&apos; does not define a constructor with parameters of paramName and message..
        /// </summary>
        internal static string SystemFailureEvaluator_ParamNameMessageConstructorNotFound {
            get {
                return ResourceManager.GetString("SystemFailureEvaluator_ParamNameMessageConstructorNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid ServiceHost type. Workflow extension can only be added to a WorkflowServiceHost instance..
        /// </summary>
        internal static string WorkflowExtensionBehavior_InvalidServiceHostType {
            get {
                return ResourceManager.GetString("WorkflowExtensionBehavior_InvalidServiceHostType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The workflow extension type &apos;{0}&apos; could not be loaded..
        /// </summary>
        internal static string WorkflowExtensionElement_ExtensionTypeNotLoaded {
            get {
                return ResourceManager.GetString("WorkflowExtensionElement_ExtensionTypeNotLoaded", resourceCulture);
            }
        }
    }
}
