// This file is used by Code Analysis to maintain SuppressMessage 
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given 
// a specific target and scoped to a namespace, type, member, etc.
//
// To add a suppression to this file, right-click the message in the 
// Error List, point to "Suppress Message(s)", and click 
// "In Project Suppression File".
// You do not need to add suppressions to this file manually.

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1702:CompoundWordsShouldBeCasedCorrectly", MessageId = "NonUser", Scope = "member", Target = "Neovolve.Toolkit.UnitTests.Communication.Security.PasswordSecurityTokenManagerTests.#CreateSecurityTokenAuthenticatorReturnsDefaultAuthenticatorForNonUserNameTokenRequirementTest()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Behaviour", Scope = "member", Target = "Neovolve.Toolkit.UnitTests.Communication.ErrorHandlerElementTests.#ErrorHandlerTypeReturnsBehaviourTypeTest()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1725:ParameterNamesShouldMatchBaseDeclaration", MessageId = "2#", Scope = "member", Target = "Neovolve.Toolkit.UnitTests.Storage.ExpirationCacheStoreBaseStub.#AddItem(System.String,System.Object,Neovolve.Toolkit.Storage.IExpirationPolicy[])")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1810:InitializeReferenceTypeStaticFieldsInline", Scope = "member", Target = "Neovolve.Toolkit.UnitTests.Instrumentation.TestTraceSourceResolver.#.cctor()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2202:Do not dispose objects multiple times", Scope = "member", Target = "Neovolve.Toolkit.UnitTests.Communication.ProxyManagerTests.#ProxyManagerCanBeDisposedMultipleTimesTest()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2202:Do not dispose objects multiple times", Scope = "member", Target = "Neovolve.Toolkit.UnitTests.Threading.LockReaderTests.#LockReaderReaderWriterLockManualDisposeTest()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2202:Do not dispose objects multiple times", Scope = "member", Target = "Neovolve.Toolkit.UnitTests.Threading.LockReaderTests.#LockReaderReaderWriterLockSlimManualDisposeTest()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2202:Do not dispose objects multiple times", Scope = "member", Target = "Neovolve.Toolkit.UnitTests.Threading.LockWriterTests.#LockWriterReaderWriterLockManualDisposeTest()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2202:Do not dispose objects multiple times", Scope = "member", Target = "Neovolve.Toolkit.UnitTests.Threading.LockWriterTests.#LockWriterReaderWriterLockSlimManualDisposeTest()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2202:Do not dispose objects multiple times", Scope = "member", Target = "Neovolve.Toolkit.UnitTests.Instrumentation.MemberTraceTests.#CallingStateOnDisposedMemberTraceThrowsExceptionTest()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2202:Do not dispose objects multiple times", Scope = "member", Target = "Neovolve.Toolkit.UnitTests.Instrumentation.MemberTraceTests.#CallingWriteCriticalWithExceptionWhenDisposedThrowsExceptionTest()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2202:Do not dispose objects multiple times", Scope = "member", Target = "Neovolve.Toolkit.UnitTests.Instrumentation.MemberTraceTests.#CallingWriteCriticalWithFormatStringWhenDisposedThrowsExceptionTest()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2202:Do not dispose objects multiple times", Scope = "member", Target = "Neovolve.Toolkit.UnitTests.Instrumentation.MemberTraceTests.#CallingWriteCriticalWithMessageWhenDisposedThrowsExceptionTest()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2202:Do not dispose objects multiple times", Scope = "member", Target = "Neovolve.Toolkit.UnitTests.Instrumentation.MemberTraceTests.#CallingWriteErrorWithExceptionWhenDisposedThrowsExceptionTest()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2202:Do not dispose objects multiple times", Scope = "member", Target = "Neovolve.Toolkit.UnitTests.Instrumentation.MemberTraceTests.#CallingWriteErrorWithFormatStringWhenDisposedThrowsExceptionTest()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2202:Do not dispose objects multiple times", Scope = "member", Target = "Neovolve.Toolkit.UnitTests.Instrumentation.MemberTraceTests.#CallingWriteErrorWithMessageWhenDisposedThrowsExceptionTest()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2202:Do not dispose objects multiple times", Scope = "member", Target = "Neovolve.Toolkit.UnitTests.Instrumentation.MemberTraceTests.#CallingWriteInformationWithFormatStringWhenDisposedThrowsExceptionTest()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2202:Do not dispose objects multiple times", Scope = "member", Target = "Neovolve.Toolkit.UnitTests.Instrumentation.MemberTraceTests.#CallingWriteInformationWithMessageWhenDisposedThrowsExceptionTest()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2202:Do not dispose objects multiple times", Scope = "member", Target = "Neovolve.Toolkit.UnitTests.Instrumentation.MemberTraceTests.#CallingWriteResumeWithFormatStringWhenDisposedThrowsExceptionTest()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2202:Do not dispose objects multiple times", Scope = "member", Target = "Neovolve.Toolkit.UnitTests.Instrumentation.MemberTraceTests.#CallingWriteResumeWithMessageWhenDisposedThrowsExceptionTest()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2202:Do not dispose objects multiple times", Scope = "member", Target = "Neovolve.Toolkit.UnitTests.Instrumentation.MemberTraceTests.#CallingWriteSuspendWithFormatStringWhenDisposedThrowsExceptionTest()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2202:Do not dispose objects multiple times", Scope = "member", Target = "Neovolve.Toolkit.UnitTests.Instrumentation.MemberTraceTests.#CallingWriteSuspendWithMessageWhenDisposedThrowsExceptionTest()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2202:Do not dispose objects multiple times", Scope = "member", Target = "Neovolve.Toolkit.UnitTests.Instrumentation.MemberTraceTests.#CallingWriteVerboseWithFormatStringWhenDisposedThrowsExceptionTest()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2202:Do not dispose objects multiple times", Scope = "member", Target = "Neovolve.Toolkit.UnitTests.Instrumentation.MemberTraceTests.#CallingWriteVerboseWithMessageWhenDisposedThrowsExceptionTest()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2202:Do not dispose objects multiple times", Scope = "member", Target = "Neovolve.Toolkit.UnitTests.Instrumentation.MemberTraceTests.#CallingWriteWarningWithExceptionWhenDisposedThrowsExceptionTest()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2202:Do not dispose objects multiple times", Scope = "member", Target = "Neovolve.Toolkit.UnitTests.Instrumentation.MemberTraceTests.#CallingWriteWarningWithFormatStringWhenDisposedThrowsExceptionTest()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2202:Do not dispose objects multiple times", Scope = "member", Target = "Neovolve.Toolkit.UnitTests.Instrumentation.MemberTraceTests.#CallingWriteWarningWithMessageWhenDisposedThrowsExceptionTest()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2202:Do not dispose objects multiple times", Scope = "member", Target = "Neovolve.Toolkit.UnitTests.Instrumentation.MemberTraceTests.#FlushOnDisposedMemberTraceThrowsExceptionTest()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2202:Do not dispose objects multiple times", Scope = "member", Target = "Neovolve.Toolkit.UnitTests.Instrumentation.MemberTraceTests.#MultipleDisposeDoesNotThrowExceptionTest()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2202:Do not dispose objects multiple times", Scope = "member", Target = "Neovolve.Toolkit.UnitTests.Threading.LockReaderTests.#LockReaderReaderWriterLockMultipleDisposeTest()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2202:Do not dispose objects multiple times", Scope = "member", Target = "Neovolve.Toolkit.UnitTests.Threading.LockReaderTests.#LockReaderReaderWriterLockSlimMultipleDisposeTest()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2202:Do not dispose objects multiple times", Scope = "member", Target = "Neovolve.Toolkit.UnitTests.Threading.LockWriterTests.#LockWriterReaderWriterLockMultipleDisposeTest()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2202:Do not dispose objects multiple times", Scope = "member", Target = "Neovolve.Toolkit.UnitTests.Threading.LockWriterTests.#LockWriterReaderWriterLockSlimMultipleDisposeTest()")]
